version: '2'

services:
  postgresql:
    container_name: postgresql
    image: 'postgres:alpine'
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
    networks:
      - discourse
    environment:
      POSTGRES_PASSWORD: pikachu
      POSTGRES_USER: pikachu
  redis:
    container_name: redis
    image: 'redis:alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - discourse
  discourse:
    container_name: discourse
    image: 'bitnami/discourse:latest'
    ports:
      - '3000:3000'
    volumes:
      - 'discourse_data:/bitnami'
    environment:
      POSTGRESQL_ROOT_USER: pikachu
      POSTGRESQL_ROOT_PASSWORD: pikachu
      DISCOURSE_POSTGRESQL_USERNAME: pikachu
      DISCOURSE_POSTGRESQL_PASSWORD: pikachu
      POSTGRESQL_HOST: postgresql
      POSTGRESQL_CLIENT_CREATE_DATABASE_NAME: bitnami_application
      POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME: bn_discourse
      POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD: bitnami1
    depends_on:
      - postgresql
      - redis
    networks:
      - discourse
  sidekiq:
    container_name: sidekiq
    image: 'bitnami/discourse:latest'
    environment:
      DISCOURSE_HOST: discourse
      DISCOURSE_POSTGRESQL_PASSWORD: pikachu
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami'
    command: 'nami start --foreground discourse-sidekiq'
    networks:
      - discourse
volumes:
  postgresql_data:
  redis_data:
  discourse_data:
  sidekiq_data:

networks:
  discourse:

